'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'tr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Türkçe ve İngilizce çeviriler
const translations: Record<Language, Record<string, string>> = {
  tr: {
    // Kayıt kuralları info çevirileri
    'nameRule.capitalized': 'Baş harfler büyük olmalı',
    'nameRule.onlyLetters': 'Sadece harf ve boşluk olmalı',
    'nameRule.twoWords': 'En az iki kelime olmalı',
    'emailRule.validFormat': 'Geçerli e-posta formatı',
    'emailRule.correctDomain': 'edu.tr uzantısı',
    'passwordRule.minLength': 'En az 8 karakter',
    'passwordRule.uppercase': 'En az bir büyük harf',
    'passwordRule.lowercase': 'En az bir küçük harf',
    'passwordRule.digit': 'En az bir rakam',
    'passwordRule.special': 'En az bir özel karakter',
    // Premium engel modalı
    'premiumBlock.title': 'Belge yükle, erişim kazan!',
    'premiumBlock.desc1': 'Sadece bir belge yükleyerek',
    'premiumBlock.desc2': '3 farklı kaynağa erişim',
    'premiumBlock.desc3': 'ödülü kazanabilirsin. Ne kadar çok paylaşırsan, o kadar çok kaynağa erişirsin!',
    'premiumBlock.uploadBtn': 'Belge Yükle',
    'premiumBlock.shareToUnlock': 'Açmak için paylaş',
    'premiumBlock.alreadyUser': 'Zaten üye misin?',
    'premiumBlock.login': 'Giriş yap',
    // Takvim
    'calendar.today': 'Bugün',
    'calendar.previous': 'Önceki',
    'calendar.next': 'Sonraki',
    'calendar.month': 'Ay',
    'calendar.week': 'Hafta',
    'calendar.day': 'Gün',
    'calendar.agenda': 'Ajanda',
    'calendar.date': 'Tarih',
    'calendar.time': 'Saat',
    'calendar.event': 'Etkinlik',
    'calendar.more': 'daha...',
    'calendar.noEventsInRange': 'Bu aralıkta ders bulunmuyor',
    // Kaynak formatları
    'resourceFormat.pdf': 'PDF',
    'resourceFormat.doc': 'DOC/DOCX',
    'resourceFormat.ppt': 'PPT/PPTX',
    'resourceFormat.jpg': 'JPG',
    'resourceFormat.jpeg': 'JPEG',
    'resourceFormat.png': 'PNG',
    'resourceFormat.xls': 'XLS/XLSX',
    'resourceFormat.video': 'Video',
    'resourceFormat.audio': 'Ses',
    'resourceFormat.image': 'Resim',
    'resourceFormat.link': 'Link',
    'resourceFormat.other': 'Diğer',
    // Kaynak kategorileri
    'general.selectOption': 'Seçiniz',
    'resourceCategory.notes': 'Ders Notları',
    'resourceCategory.books': 'Kitaplar',
    'resourceCategory.articles': 'Makaleler',
    'resourceCategory.videos': 'Videolar',
    'resourceCategory.presentations': 'Sunumlar',
    'resourceCategory.examQuestions': 'Sınav Soruları',
    'resourceCategory.projects': 'Projeler',
    'resourceCategory.other': 'Diğer',
    // Akademik seviyeler
    'academicLevel.associate': 'Ön Lisans',
    'academicLevel.bachelor': 'Lisans',
    'academicLevel.master': 'Yüksek Lisans',
    'academicLevel.phd': 'Doktora',
    // Çok Yakında
    'comingSoon.title': 'Çok Yakında!',
    'comingSoon.description': 'Bu sayfa ve özellikler çok yakında aktif olacak. Takipte kalın!',
    'comingSoon.backToHome': 'Ana Sayfaya Dön',
    'nav.listings': 'Ders İlanları',
    'nav.lessons': 'Derslerim',
    'nav.createListing': 'İlan Ver',
    'nav.createLesson': 'Ders Oluştur',
    'nav.login': 'Giriş Yap',
    'nav.register': 'Kayıt Ol',
    'nav.profile': 'Profilim',
    'nav.messages': 'Mesajlarım',
    'nav.myLessons': 'Derslerim',
    'nav.myListings': 'Ders İlanlarım',
    'nav.logout': 'Çıkış Yap',
    'nav.instructors': 'Eğitmenler',
    'nav.events': 'Etkinlikler',
    'nav.eventsAdmin': 'Etkinlik Yönetimi',
    'nav.resources': 'Kaynaklar',
    'nav.projects': 'Projeler',
    'adminClubs': 'Kulüp Yönetimi',
    'adminClubs.addButton': 'Kulüp Ekle',
    'adminClubs.subtitle': 'Kulüpleri görüntüleyin, düzenleyin veya silin.',
    'nav.myProjects': 'Projelerim',
    'myProjects.noProjects': 'Henüz projeniz yok.',
    'myProjects.addNewProject': 'Yeni proje ekleyin',
    'nav.clubs': 'Kulüpler',
    'nav.myClub': 'Kulübüm',
    'nav.contact': 'İletişim',
    'nav.about': 'Hakkımızda',
    'nav.faq': 'Sıkça Sorulan Sorular',
    'nav.blog': 'Blog',
    'nav.language': 'Dil',
    'nav.mainMenu': 'Ana Menü',
    'nav.account': 'Hesabım',
    'nav.openMenu': 'Menüyü aç',
    'nav.closeMenu': 'Menüyü kapat',
    'nav.comingSoon': 'Yakında',
    'nav.aiAssistant': 'Soru Hazırlat',
    'nav.aiNotes': 'Not Çıkart',
    'events.title': 'Etkinlikler',
    'events.subtitle': 'Kulüplerin tüm etkinliklerini keşfedin ve filtreleyin.',
    'events.searchPlaceholder': 'Etkinlik veya anahtar kelime ara',
    'events.searchButton': 'Ara',
    'events.filtersTitle': 'Filtreler',
    'events.filterLocation': 'Konum',
    'events.allLocations': 'Tüm Konumlar',
    'events.filterUniversity': 'Üniversite',
    'events.filterClub': 'Kulüp',
    'events.filterCategory': 'Kategori',
    'events.filterDateFrom': 'Başlangıç Tarihi',
    'events.filterDateTo': 'Bitiş Tarihi',
    'events.resetFilters': 'Filtreleri Sıfırla',
    'events.noResults': 'Kriterlere uygun etkinlik bulunamadı.',
    'events.allUniversities': 'Tüm Üniversiteler',
    'events.allClubs': 'Tüm Kulüpler',
    'events.allCategories': 'Tüm Kategoriler',
    'events.eventDate': 'Tarih',
    'events.locationLabel': 'Konum',
    'events.resourcesLabel': 'Kaynaklar',
    'events.associatedClubs': 'İlgili Kulüpler',
    'events.detail.back': 'Etkinliklere Dön',
    'events.detail.organizedBy': 'Düzenleyen',
    'events.detail.universities': 'İlgili Üniversiteler',
    'events.detail.resourcesTitle': 'Etkinlik Kaynakları',
    'events.detail.resourcesEmpty': 'Bu etkinlik için paylaşılmış kaynak bulunmuyor.',
    'events.detail.clubsTitle': 'İlgili Kulüpler',
    'events.detail.clubsEmpty': 'Bu etkinlik için ilişkilendirilmiş kulüp bulunmuyor.',
    'events.detail.loading': 'Etkinlik yükleniyor...',
    'events.detail.error': 'Etkinlik yüklenirken bir hata oluştu.',
    'events.detail.notFound': 'Etkinlik bulunamadı.',
    'events.admin.loginTitle': 'Etkinlik Yönetimi Girişi',
    'events.admin.emailLabel': 'Yönetici E-posta',
    'events.admin.emailPlaceholder': 'Örn: etkinlikkavunla',
    'events.admin.passwordLabel': 'Yönetici Şifre',
    'events.admin.passwordPlaceholder': 'Şifrenizi girin',
    'events.admin.loggingIn': 'Giriş yapılıyor...',
    'events.admin.loginButton': 'Giriş Yap',
    'events.admin.loginError': 'Giriş başarısız. Bilgileri kontrol edin.',
    'events.admin.loginSuccess': 'Giriş başarılı',
    'events.admin.addTitle': 'Etkinlik Ekle',
    'events.admin.listTitle': 'Etkinlikler',
    'events.admin.manageDescription': 'Etkinlikleri düzenleyin veya silin.',
    'events.admin.addNewButton': 'Etkinlik Ekle',
    'events.admin.logoutButton': 'Çıkış Yap',
    'events.admin.titleLabel': 'Etkinlik Başlığı',
    'events.admin.dateLabel': 'Etkinlik Tarihi ve Saati',
    'events.admin.categoryLabel': 'Kategori',
    'events.admin.locationLabel': 'Konum',
    'events.admin.photoLabel': 'Fotoğraf',
    'events.admin.descriptionLabel': 'Açıklama',
    'events.admin.resourcesLabel': 'Kaynaklar / Linkler',
    'events.admin.resourcesHint': 'Her satıra bir bağlantı ya da kaynak ekleyin.',
    'events.admin.resourcesPlaceholder': 'https://...',
    'events.admin.tableDate': 'Tarih',
    'events.admin.tableCategory': 'Kategori',
    'events.admin.tableLocation': 'Konum',
    'events.admin.tableActions': 'İşlemler',
    'events.admin.editButton': 'Düzenle',
    'events.admin.deleteButton': 'Sil',
    'events.admin.deleteConfirm': 'Bu etkinliği silmek istediğinize emin misiniz?',
    'events.admin.deleteSuccess': 'Etkinlik başarıyla silindi.',
    'events.admin.deleteError': 'Etkinlik silinirken hata oluştu.',
    'events.admin.updateSuccess': 'Etkinlik başarıyla güncellendi.',
    'events.admin.updateError': 'Etkinlik güncellenirken hata oluştu.',
    'events.admin.noEvents': 'Henüz kayıtlı etkinlik bulunmuyor.',
    'events.admin.editTitle': 'Etkinliği Düzenle',
    'events.admin.closeButton': 'Kapat',
    'events.admin.saveChangesButton': 'Değişiklikleri Kaydet',
    'events.admin.clubSelectTitle': 'Kulüp Seçimi',
    'events.admin.loadingClubs': 'Kulüpler yükleniyor...',
    'events.admin.noClubs': 'Kayıtlı kulüp bulunamadı.',
    'events.admin.loadClubsError': 'Kulüpler yüklenirken hata oluştu.',
    'events.admin.dateRequired': 'Etkinlik tarihi seçilmelidir.',
    'events.admin.selectClubError': 'En az bir kulüp seçmelisiniz.',
    'events.admin.createSuccess': 'Etkinlik başarıyla oluşturuldu.',
    'events.admin.createError': 'Etkinlik oluşturulamadı.',
    'events.admin.saving': 'Kaydediliyor...',
    'events.admin.saveButton': 'Etkinliği Kaydet',
    'ai.question.description': 'PDF, metin veya görsel içerikleri yükleyip dersiniz için test, klasik veya kısa cevaplı sorular hazırlatabilirsiniz. OpenAI entegrasyonu tamamlandığında sonuçlar otomatik olarak hazırlanacaktır.',
    'ai.question.uploadLabel': 'Çalışma materyalini yükleyin',
    'ai.question.uploadHint': 'PDF, DOCX, TXT veya görsel dosya seçin',
    'ai.question.uploadSubHint': 'Sürükleyip bırakabilir veya tıklayarak yükleyebilirsiniz (maks. 15MB)',
    'ai.question.notesLabel': 'Ek notlarınız (isteğe bağlı)',
    'ai.question.notesPlaceholder': 'Örneğin: Çoktan seçmeli 5 soru üret, Bloom taksonomisine göre zorluk seviyesi orta olsun.',
    'ai.question.countLabel': 'Soru adedi',
    'ai.question.typeLabel': 'Soru türü',
    'ai.question.typeMultipleChoice': 'Test (şıklı)',
    'ai.question.typeOpenEnded': 'Klasik',
    'ai.question.choiceCountLabel': 'Şık sayısı',
    'ai.question.generateButton': 'Soruları Hazırla',
    'ai.question.generating': 'Hazırlanıyor...',
    'ai.question.howItWorksTitle': 'Nasıl çalışacak?',
    'ai.question.howItWorksDescription': 'OpenAI API anahtarı eklendiğinde, yüklediğiniz içerik otomatik olarak analiz edilecek ve seçtiğiniz kriterlere uygun sorular burada listelenecek.',
    'ai.question.tipTitle': 'İpucu',
    'ai.question.tipLine1': 'Pdf, ders notu veya görselleri tek seferde yükleyebilirsiniz.',
    'ai.question.tipLine2': 'Ek not alanına soru türü, sınıf seviyesi veya konu başlıklarını yazın.',
    'ai.question.tipLine3': 'Entegrasyon sonrası tüm sonuçlar JSON olarak saklanabilir.',
    'ai.question.resultsTitle': 'Hazırlanan Sorular',
    'ai.question.resultsPlaceholder': 'Henüz soru oluşturulmadı. İçerik ekleyip soruları hazırlayabilirsiniz.',
    'ai.question.answerKeyTitle': 'Cevap Anahtarı',
    'ai.question.answerKeyShow': 'Anahtarı Göster',
    'ai.question.answerKeyHide': 'Anahtarı Gizle',
    'ai.question.answerUnavailable': 'Cevap henüz mevcut değil.',
    'ai.question.textLabel': 'Metni yapıştırın (isteğe bağlı)',
    'ai.question.textPlaceholder': 'Örneğin: Ders notunuzun ilgili bölümünü buraya kopyalayabilirsiniz.',
    'ai.notes.description': 'PDF, metin veya görsel ders materyallerini yükleyerek dakikalar içinde çalışma notlarına dönüştürün. Yapay zekâ, dersinize uygun kısaltılmış notlar çıkarır.',
    'ai.notes.uploadLabel': 'Ders materyalini yükleyin',
    'ai.notes.uploadHint': 'PDF, DOCX, TXT veya görsel dosya seçin',
    'ai.notes.uploadSubHint': 'Sürükleyip bırakabilir veya tıklayarak yükleyebilirsiniz (maks. 15MB)',
    'ai.notes.promptsLabel': 'Vurgulamak istediğiniz başlıklar (isteğe bağlı)',
    'ai.notes.promptsPlaceholder': 'Örneğin: Ana kavramlar, tarihsel gelişim ve sayısal sonuçlara odaklan.',
    'ai.notes.toneLabel': 'Not stili',
    'ai.notes.toneAcademic': 'Akademik',
    'ai.notes.toneSimple': 'Anlaşılır',
    'ai.notes.generateButton': 'Not Çıkart',
    'ai.notes.generating': 'Notlar hazırlanıyor...',
    'ai.notes.howItWorksTitle': 'İşleyiş',
    'ai.notes.howItWorksDescription': 'Yüklediğiniz içerik analiz edilerek seçtiğiniz tona uygun ders notları oluşturulur.',
    'ai.notes.tipTitle': 'İpucu',
    'ai.notes.tipLine1': 'Anlaşılır ton hızlı tekrar notları için idealdir.',
    'ai.notes.tipLine2': 'Akademik ton, detaylı ve resmi özetler için uygundur.',
    'ai.notes.tipLine3': 'Ek not alanına sınav kapsamı veya uzunluk tercihini yazabilirsiniz.',
    'ai.notes.resultsTitle': 'Oluşturulan Notlar',
    'ai.notes.resultsPlaceholder': 'Henüz not oluşturulmadı. İçerik ekleyip not çıkartabilirsiniz.',
    'ai.notes.textLabel': 'Metni yapıştırın (isteğe bağlı)',
    'ai.notes.textPlaceholder': 'Örneğin: Dersinizin önemli kısımlarını buraya yazabilirsiniz.',
    'ai.common.fileSelected': 'Seçilen dosya',
    'ai.common.removeFile': 'Dosyayı kaldır',
    'ai.common.noFileSelected': 'Henüz dosya seçilmedi',
    'ai.common.missingSource': 'Lütfen bir dosya yükleyin veya metin girin.',
    'ai.common.unexpectedError': 'İşlem sırasında beklenmedik bir hata oluştu. Lütfen tekrar deneyin.',
    'ai.common.apiError': 'İşlem sırasında bir hata oluştu: {{message}}',
    'nav.notifications': 'Bildirimler',
    'clubs.title': 'Kulüpler',
    'clubs.addClub': 'Kulüp Ekle',
    'clubs.searchPlaceholder': 'Ara (isim, anahtar kelime)',
    'clubs.categoryAll': 'Kategori (Tümü)',
    'clubs.universityAll': 'Üniversite (Tümü)',
    'clubs.contactButton': 'İletişime Geç',
    'clubs.noResults': 'Kriterlere uygun kulüp bulunamadı.',
    'clubs.loading': 'Kulüpler yükleniyor...',
    'clubs.viewDetails': 'Detayları Görüntüle',
    'clubs.join': 'Katıl',
    'clubs.leave': 'Ayrıl',
    'clubs.members': 'Üyeler',
    'clubs.owner': 'Sahibi',
    'clubs.contact': 'İletişim',
    'clubs.about': 'Hakkında',
    'clubs.category.general': 'Genel',
    'clubs.category.web': 'Web',
    'clubs.category.mobile': 'Mobil',
    'clubs.category.desktop': 'Masaüstü',
    'clubs.category.ai': 'Yapay Zeka',
    'clubs.category.game': 'Oyun',
    'clubs.category.dataScience': 'Veri Bilimi',
    'clubs.category.cyberSecurity': 'Siber Güvenlik',
    'clubs.category.other': 'Diğer',
    'clubs.activities': 'Etkinlikler',
    'clubs.announcements': 'Duyurular',
    'clubs.events': 'Etkinlikler',
    'clubs.eventsEmpty': 'Bu kulüp için etkinlik bulunmuyor.',
    'clubs.photos': 'Fotoğraflar',
    'clubs.documents': 'Dokümanlar',
    'clubs.discussions': 'Tartışmalar',
    'clubs.settings': 'Ayarlar',
    // Genel
    'general.search': 'Ara',
    'general.filter': 'Filtrele',
    'general.filters': 'Filtreler',
    'general.searchResources': 'Kaynak Ara',
    'general.filterResources': 'Kaynakları Filtrele',
    'general.allResources': 'Tüm Kaynaklar',
    'general.allUniversities': 'Tüm Üniversiteler',
    'general.shareResource': 'Kaynak Paylaş',
    'general.resourceTitle': 'Kaynak Başlığı',
    'general.resourceDescription': 'Kaynak Açıklaması',
    'general.resourceType': 'Kaynak Türü',
    'general.resourceLink': 'Kaynak Bağlantısı',
    'general.resourceFile': 'Kaynak Dosyası',
    'general.uploadResource': 'Kaynak Yükle',
    'general.resourceCategory': 'Kategori',
    'general.resourceSubject': 'Konu',
    'general.course': 'Ders',
    'general.coursePlaceholder': 'ör. Matematik I / Calculus',
    'general.resourceLevel': 'Seviye',
    'general.resourceLanguage': 'Dil',
    'general.resourceFormat': 'Format',
    'general.fileUploadClickOrDrag': 'Dosya yüklemek için tıklayın veya sürükleyip bırakın',
    'general.fileUploadFormats': 'PDF, DOC, PPT, XLS, MP4, MP3, JPG, PNG (Max 50MB)',
    'general.tagsPlaceholder': 'matematik, calculus, türev, integral',
    'general.resourceAuthor': 'Yazar',
    'general.resourceDate': 'Tarih',
    'general.resourceSize': 'Boyut',
    'general.resourceDownload': 'İndir',
    'general.resourceView': 'Görüntüle',
    'general.resourceShare': 'Paylaş',
    'general.resourceSave': 'Kaydet',
    'general.resourceDelete': 'Sil',
    'general.resourceEdit': 'Düzenle',
    'general.resourceReport': 'Bildir',
    'general.resourceLike': 'Beğen',
    'general.resourceComment': 'Yorum Yap',
    'general.resourceComments': 'Yorumlar',
    'general.resourceRating': 'Değerlendirme',
    'general.resourceViews': 'Görüntülenme',
    'general.resourceDownloads': 'İndirme',
    'general.resourceShares': 'Paylaşım',
    'general.resourceLikes': 'Beğeni',
    'general.resourceDislikes': 'Beğenmeme',
    'general.resourceFavorites': 'Favoriler',
    'general.resourceBookmarks': 'Yer İmleri',
    'general.preview': 'Önizle',
    'general.downloadFile': 'Dosyayı İndir',
    'general.resourceRelated': 'İlgili Kaynaklar',
    'general.resourcePopular': 'Popüler Kaynaklar',
    'general.resourceRecent': 'Son Eklenen Kaynaklar',
    'general.resourceFeatured': 'Öne Çıkan Kaynaklar',
    'general.resourceRecommended': 'Önerilen Kaynaklar',
    'general.resourceTrending': 'Trend Kaynaklar',
    'general.resourceNew': 'Yeni Kaynaklar',
    'general.resourceMostViewed': 'En Çok Görüntülenen',
    'general.resourceMostDownloaded': 'En Çok İndirilen',
    'general.resourceMostShared': 'En Çok Paylaşılan',
    'general.resourceMostLiked': 'En Çok Beğenilen',
    'general.resourceMostCommented': 'En Çok Yorum Yapılan',
    'general.resourceMostRated': 'En Çok Değerlendirilen',
    'general.resourceHighestRated': 'En Yüksek Puanlı',
    'general.resourceLowestRated': 'En Düşük Puanlı',
    'general.resourceCategories': 'Kategoriler',
    'general.resourceSubjects': 'Konular',
    'general.resourceLevels': 'Seviyeler',
    'general.resourceLanguages': 'Diller',
    'general.resourceFormats': 'Formatlar',
    'general.resourceAuthors': 'Yazarlar',
    'general.resourceDates': 'Tarihler',
    'general.resourceSizes': 'Boyutlar',
    'general.resourceTags': 'Etiketler',
    'general.resourceKeywords': 'Anahtar Kelimeler',
    'general.resourceSearch': 'Kaynak Arama',
    'general.resourceAdvancedSearch': 'Gelişmiş Arama',
    'general.resourceSearchResults': 'Arama Sonuçları',
    'general.resourceSearchNoResults': 'Arama Sonucu Bulunamadı',
    'general.resourceSearchTips': 'Arama İpuçları',
    'general.resourceSearchFilters': 'Arama Filtreleri',
    'general.resourceSearchSort': 'Sıralama',
    'general.resourceSearchSortBy': 'Sıralama Kriteri',
    'general.resourceSearchSortOrder': 'Sıralama Düzeni',
    'general.resourceSearchSortAsc': 'Artan',
    'general.resourceSearchSortDesc': 'Azalan',
    'general.price': 'Fiyat',
    'general.duration': 'Süre',
    'general.method': 'Yöntem',
    'general.submit': 'Gönder',
    'general.cancel': 'İptal',
    'general.save': 'Kaydet',
    'general.edit': 'Düzenle',
    'general.delete': 'Sil',
    'common.edit': 'Düzenle',
    'common.delete': 'Sil',
    'common.createProject': 'Proje Ekle',
    'project.position': 'Pozisyon',
    'project.positionPlaceholder': 'ör. React Geliştirici',
    'category.all': 'Tüm Kategoriler',
    'category.general': 'Genel',
    'category.web': 'Web',
    'category.mobile': 'Mobil',
    'category.desktop': 'Masaüstü',
    'category.other': 'Diğer',
    'category.ai': 'Yapay Zeka',
    'category.game': 'Oyun',
    'category.dataScience': 'Veri Bilimi',
    'category.cyberSecurity': 'Siber Güvenlik',
    'category.blockchain': 'Blockchain',
    'category.iot': 'IoT',
    'category.arvr': 'AR/VR',
    'category.robotics': 'Robotik',
    'category.ecommerce': 'E-Ticaret',
    'category.fintech': 'FinTech',
    'category.health': 'Sağlık',
    'category.education': 'Eğitim',
    'category.cloud': 'Cloud',
    'category.devops': 'DevOps',
    'category.dataEngineering': 'Data Engineering',
    'category.hardware': 'Donanım',
        'filter.onlyMine': 'Sadece Benim',
    'project.detail': 'Proje Detayı',
    'project.contact': 'İletişim',
    'project.technologies': 'Teknolojiler',
    'project.requirements': 'Gereksinimler',
    'project.benefits': 'Sağlayacakları',
    'project.url': 'Proje URL',
    'project.notFound': 'Proje bulunamadı',
    'status.ongoing': 'Devam Ediyor',
    'status.completed': 'Tamamlandı',
    'status.planned': 'Planlanıyor',
    'status.active': 'Aktif',
    'status.inactive': 'Pasif',
    'general.back': 'Geri',
    'general.next': 'İleri',
    'general.finish': 'Bitir',
    'general.loading': 'Yükleniyor...',
    'general.error': 'Hata',
    'general.success': 'Başarılı',
    'general.noResults': 'Sonuç bulunamadı',
    'general.clearFilters': 'Filtreleri Temizle',
    'general.showAll': 'Tümünü Göster',
    'general.showFavorites': 'Favorileri Göster',
    'general.hourlyRate': 'Saatlik Ücret',
    'general.priceLabel': 'Ücret',
    'general.methodLabel': 'Yöntem',
    'general.frequencyLabel': 'Sıklık',
    'general.instructorFromLabel': 'Dersi Aldığım Eğitmen',
    'general.lessonFrequency': 'Ders Sıklığı',
    'frequency.daily': 'Günlük',
    'frequency.weekly': 'Haftalık',
    'frequency.monthly': 'Aylık',
    'frequency.flexible': 'Esnek',
    'general.lessonMethod': 'Ders Yöntemi',
    'general.instructor': 'Eğitmen',
    'general.university': 'Üniversite',
    'general.department': 'Bölüm',
    'general.notSpecified': 'Belirtilmemiş',
    'general.academicLevel': 'Akademik Seviye',
    'general.expertise': 'Uzmanlık Alanı',
    'general.description': 'Açıklama',
    'general.contactTeacher': 'Eğitmen ile İletişime Geç',
    'general.bookAppointment': 'Randevu Al',
    'general.sendMessage': 'Mesaj Gönder',
    'general.sendEmail': 'Mail Gönder',
    'general.goBack': 'Geri Dön',
    'general.backToListings': 'İlanlara Geri Dön',
    'general.openListings': 'Açık İlanlar',
    'general.showAllListings': 'Tüm İlanları Göster',
    'general.processing': 'İşleniyor...',
    'general.publish': 'Yayınla',
    'general.accessDenied': 'Erişim Engellendi',
    'general.accessDeniedMessage': 'Bu sayfaya erişmek için eğitmen hesabıyla giriş yapmanız gerekmektedir.',
    'general.goToHomepage': 'Ana Sayfaya Dön',
    'general.online': 'Online',
    'general.faceToFace': 'Yüz Yüze',
    'general.hybrid': 'Hibrit (Online + Yüz Yüze)',
    'general.createListingTitle': 'Yeni İlan Oluştur',
    'listings.universityListings': 'Üniversite İlanları',
    'listings.exploreTeacherLessons': 'Eğitmen Derslerini Keşfet',
    'general.listingTitle': 'İlan Başlığı',
    'general.listingTitlePlaceholder': 'Örn: Python Programlama Dersi',
    'general.listingDescription': 'Detaylı Açıklama',
    'general.listingDescriptionPlaceholder': 'Ders içeriği ve kendiniz hakkında bilgi verin...',
    'general.hourlyPrice': 'Ders Ücreti (₺/Saat)',
    'general.hours': 'Saat',
    'general.lessonDurationHours': 'Ders Süresi (Saat)',
    'general.hourlyPricePlaceholder': 'Örn: 150',
    'general.instructorFrom': 'Dersi Aldığınız Eğitmen',
    'general.instructorFromPlaceholder': 'Örn: Ankara Üniversitesi, Prof. Dr. Ahmet Yılmaz',
    'general.publishListing': 'İlanı Yayınla',
    'general.listingCreated': 'İlanınız başarıyla oluşturuldu!',
    'general.searchPlaceholder': 'İlan ara...',
    'general.filterOptions': 'Filtreleme Seçenekleri',
    'general.sort': 'Sıralama',
    'general.newest': 'En Yeni',
    'general.oldest': 'En Eski',
    'general.priceAsc': 'Fiyat (Artan)',
    'general.priceDesc': 'Fiyat (Azalan)',
    'general.minPrice': 'Minimum Ücret (₺)',
    'general.maxPrice': 'Maksimum Ücret (₺)',
    'general.allMethods': 'Tüm yöntemler',
    'general.minPricePlaceholder': 'Minimum fiyat',
    'general.maxPricePlaceholder': 'Maksimum fiyat',
    'general.resultsFound': 'ilan bulundu',
    'general.unknown': 'Bilinmiyor',
    'general.noResultsFound': 'Arama Sonuçları Bulunamadı',
    
    'general.noResultsForSearch': 'Aradığınız kriterlere uygun sonuç bulunamadı.',
    'general.downloadStarted': 'İndirme başladı.',
    'general.downloadError': 'İndirme sırasında bir hata oluştu. Lütfen tekrar deneyin.',
    'general.fileNotFound': 'Dosya bulunamadı. Bu kaynak için indirilebilir bir dosya yok.',
    'general.noListingsYet': 'Henüz İlan Bulunmuyor',
    'general.listingsWillAppear': 'Üniversitenizdeki eğitmenler ilan verdikçe burada görüntülenecektir.',
    'general.noProjectsYet': 'Henüz hiç projeniz yok.',
    'general.addYourFirstProject': 'İlk projenizi ekleyin',
    'general.noClubsYet': 'Henüz hiç kulübünüz yok.',
    'general.addYourFirstClub': 'İlk kulübünüzü oluşturun',
    'general.clubName': 'Kulüp Adı',
    'general.clubCategory': 'Kulüp Kategorisi',
    'general.clubDescription': 'Kulüp Açıklaması',
    'general.clubUniversity': 'Üniversite',
    'general.clubCreate': 'Kulüp Oluştur',
    'general.clubUpdate': 'Kulübü Güncelle',
    'general.clubDelete': 'Kulübü Sil',
    'general.clubSave': 'Kaydet',
    'general.clubCancel': 'İptal',
    'general.clubNameRequired': 'Kulüp adı gereklidir',
    'general.clubCreated': 'Kulüp başarıyla oluşturuldu!',
    'general.clubUpdated': 'Kulüp başarıyla güncellendi!',
    'general.clubDeleted': 'Kulüp başarıyla silindi!',
    'general.clubSearch': 'Kulüp ara...',
    'general.clubSearchPlaceholder': 'Kulüp adı veya kategori ara...',
    'general.clubCategoryAll': 'Tüm Kategoriler',
    'general.clubUniversityAll': 'Tüm Üniversiteler',
    'general.clubNoResults': 'Aradığınız kriterlere uygun kulüp bulunamadı.',
    'general.clubAdd': 'Kulüp Ekle',
    'general.clubJoin': 'Katıl',
    'general.clubLeave': 'Ayrıl',
    'general.clubMembers': 'Üyeler',
    'general.clubOwner': 'Sahibi',
    'general.clubDetails': 'Kulüp Detayları',
    'general.clubContact': 'İletişim',
    'general.clubActivities': 'Etkinlikler',
    'general.clubAnnouncements': 'Duyurular',
    'general.clubEvents': 'Etkinlikler',
    'general.clubPhotos': 'Fotoğraflar',
    'general.clubDocuments': 'Dokümanlar',
    'general.clubDiscussions': 'Tartışmalar',
    'general.clubSettings': 'Ayarlar',
    'general.clubEdit': 'Kulübü Düzenle',
    'general.clubDeleteConfirm': 'Bu kulübü silmek istediğinizden emin misiniz?',
    'general.clubDeleteConfirmDesc': 'Bu işlem geri alınamaz.',
    'general.clubDeleteYes': 'Evet, Sil',
    'general.clubDeleteNo': 'Hayır',
    'notifications.title': 'Bildirimlerim',
    'notifications.all': 'Tüm Bildirimler',
    'notifications.unread': 'Okunmamış Bildirimler',
    'notifications.read': 'Okunmuş Bildirimler',
    'notifications.viewDetails': 'Detayları Görüntüle',
    'notifications.noNotifications': 'Bildirim bulunamadı',
    'notifications.markAsRead': 'Okundu olarak işaretle',
    'notifications.markAsUnread': 'Okunmadı olarak işaretle',
    'notifications.delete': 'Sil',
    'notifications.deleteConfirm': 'Bu bildirimi silmek istediğinizden emin misiniz?',
    'notifications.deleteSuccess': 'Bildirim silindi',
    'notifications.deleteError': 'Bildirim silinirken hata oluştu',
    'notifications.loading': 'Bildirimler yükleniyor...',
    'notifications.error': 'Bildirimler yüklenirken hata oluştu',
    'notifications.empty': 'Henüz bildiriminiz yok',
    'notifications.loginRequired': 'Bildirimleri görmek için giriş yapmalısınız',
    'notifications.goToLogin': 'Giriş Yap',
    'notifications.markAllAsRead': 'Tümünü Okundu İşaretle',
    'notifications.markAllAsReadSuccess': 'Tüm bildirimler okundu olarak işaretlendi',
    'notifications.markAllAsReadError': 'Bildirimler işaretlenirken hata oluştu',
    'notifications.refresh': 'Yenile',
    'notifications.new': 'Yeni',
    'notifications.older': 'Daha Eski',
    'notifications.showMore': 'Daha Fazla Göster',
    'notifications.showLess': 'Daha Az Göster',
    'notifications.filterBy': 'Filtrele',
    'notifications.sortBy': 'Sırala',
    'notifications.sortByDate': 'Tarihe Göre',
    'notifications.sortByType': 'Türe Göre',
    'notifications.sortByStatus': 'Duruma Göre',
    'notifications.typeAll': 'Tüm Türler',
    'notifications.typeSystem': 'Sistem',
    'notifications.typeMessage': 'Mesaj',
    'notifications.typeListing': 'İlan',
    'notifications.typeProject': 'Proje',
    'notifications.typeClub': 'Kulüp',
    'notifications.typeLesson': 'Ders',
    'notifications.typeResource': 'Kaynak',
    'notifications.timeAgo.minutes': '{count} dakika önce',
    'notifications.timeAgo.hours': '{count} saat önce', 
    'notifications.timeAgo.days': '{count} gün önce',
    'instructor.expertise': 'Uzmanlık Alanı',
    'instructor.experience': 'Deneyim',
    'instructor.rating': 'Değerlendirme',
    'instructor.ratingCount': 'Değerlendirme Sayısı',
    'instructor.averageRating': 'Ortalama Puan',
    'instructor.contact': 'İletişim',
    'instructor.viewLessons': 'Dersleri Görüntüle',
    'instructor.sendMessage': 'Mesaj Gönder',
    'instructor.writeReview': 'Değerlendirme Yap',
    'instructor.reviews': 'Değerlendirmeler',
    'instructor.noReviews': 'Henüz değerlendirme yok',
    'instructor.addReview': 'Değerlendirme Ekle',
    'instructor.editReview': 'Değerlendirmeyi Düzenle',
    'instructor.deleteReview': 'Değerlendirmeyi Sil',
    'instructor.reviewTitle': 'Değerlendirme Başlığı',
    'instructor.reviewComment': 'Değerlendirme Yorumu',
    'instructor.reviewRating': 'Puan',
    'instructor.reviewDate': 'Değerlendirme Tarihi',
    'instructor.reviewHelpful': 'Yardımcı',
    'instructor.reviewNotHelpful': 'Yardımcı Değil',
    'instructor.reviewReport': 'Bildir',
    'instructor.reviewEdit': 'Düzenle',
    'instructor.reviewDelete': 'Sil',
    'instructor.reviewSubmit': 'Değerlendirmeyi Gönder',
    'instructor.reviewUpdate': 'Değerlendirmeyi Güncelle',
    'instructor.reviewCancel': 'İptal',
    'instructor.reviewSuccess': 'Değerlendirmeniz başarıyla gönderildi',
    'instructor.reviewUpdateSuccess': 'Değerlendirmeniz başarıyla güncellendi',
    'instructor.reviewDeleteSuccess': 'Değerlendirmeniz başarıyla silindi',
    'instructor.reviewDeleteError': 'Değerlendirme silinirken hata oluştu',
    'instructor.reviewLoadError': 'Değerlendirmeler yüklenirken hata oluştu',
    'instructor.reviewSubmitError': 'Değerlendirme gönderilirken hata oluştu',
    'instructor.reviewUpdateError': 'Değerlendirme güncellenirken hata oluştu',
    'instructor.reviewAlreadyExists': 'Bu ders için zaten değerlendirme yaptınız',
    'instructor.reviewNotEligible': 'Bu eğitmenle ders almadığınız için değerlendirme yapamazsınız',
    'instructor.reviewSelectLesson': 'Değerlendirme yapmak için ders seçin',
    'instructor.reviewSelectRating': 'Puan seçin',
    'instructor.reviewEnterTitle': 'Başlık girin',
    'instructor.reviewEnterComment': 'Yorum girin',
    'instructor.reviewMinLength': 'Yorum en az 10 karakter olmalıdır',
    'instructor.reviewMaxLength': 'Yorum en fazla 500 karakter olabilir',
    'instructor.reviewTitleMinLength': 'Başlık en az 5 karakter olmalıdır',
    'instructor.reviewTitleMaxLength': 'Başlık en fazla 100 karakter olabilir',
    'instructor.reviewThanks': 'Değerlendirmeniz için teşekkür ederiz',
    'instructor.reviewHelpfulThanks': 'Oyunuz için teşekkür ederiz',
    'instructor.reviewAlreadyVoted': 'Bu değerlendirmeye zaten oy verdiniz',
    'instructor.reviewVoteError': 'Oy verilirken hata oluştu',
    'instructor.reviewLoadMore': 'Daha Fazla Yükle',
    'instructor.reviewShowLess': 'Daha Az Göster',
    'instructor.reviewSortBy': 'Sırala',
    'instructor.reviewSortByDate': 'Tarihe Göre',
    'instructor.reviewSortByRating': 'Puana Göre',
    'instructor.reviewSortByHelpful': 'Yardımcı Olana Göre',
    'instructor.reviewSortAsc': 'Artan',
    'instructor.reviewSortDesc': 'Azalan',
    'instructor.reviewFilterBy': 'Filtrele',
    'instructor.reviewFilterByRating': 'Puana Göre',
    'instructor.reviewFilterByDate': 'Tarihe Göre',
    'instructor.reviewFilterByHelpful': 'Yardımcı Olana Göre',
    'instructor.reviewFilterAll': 'Tümü',
    'instructor.reviewFilterPositive': 'Pozitif',
    'instructor.reviewFilterNegative': 'Negatif',
    'instructor.reviewFilterRecent': 'Son',
    'instructor.reviewFilterOldest': 'Eski',
    'instructor.reviewFilterMostHelpful': 'En Yardımcı',
    'instructor.reviewFilterLeastHelpful': 'En Az Yardımcı',
    'instructor.reviewFilterHighRating': 'Yüksek Puan',
    'instructor.reviewFilterLowRating': 'Düşük Puan',
    'instructor.reviewFilterMediumRating': 'Orta Puan',
    'instructor.reviewFilterWithComment': 'Yorumlu',
    'instructor.reviewFilterWithoutComment': 'Yorumsuz',
    'instructor.reviewFilterVerified': 'Doğrulanmış',
    'instructor.reviewFilterUnverified': 'Doğrulanmamış',
    'instructor.reviewFilterMyReviews': 'Benim Değerlendirmelerim',
    'instructor.reviewFilterOthers': 'Başkalarının Değerlendirmeleri',
    'instructor.reviewFilterFriends': 'Arkadaşların Değerlendirmeleri',
    'instructor.reviewFilterTeachers': 'Eğitmen Değerlendirmeleri',
    'instructor.reviewFilterStudents': 'Öğrenci Değerlendirmeleri',
    'instructor.reviewFilterAllUsers': 'Tüm Kullanıcılar',
    'instructor.reviewFilterAllTypes': 'Tüm Türler',
    'instructor.reviewFilterText': 'Metin',
    'instructor.reviewFilterPhoto': 'Fotoğraf',
    'instructor.reviewFilterVideo': 'Video',
    'instructor.reviewFilterAudio': 'Ses',
    'instructor.reviewFilterDocument': 'Doküman',
    'instructor.reviewFilterLink': 'Link',
    'instructor.reviewFilterOther': 'Diğer',
    'general.listingDetails': 'İlan Detayları',
    'general.lessonDetails': 'Ders Detayları',
    'general.teacherInfo': 'Eğitmen Bilgisi',
    'general.additionalInfo': 'Ek Bilgiler',
    'general.allListings': 'Tüm İlanları',
    'general.hour': 'Saat',
    'general.postDate': 'Gönderi Tarihi',
    'general.viewDetails': 'Detayları Gör',
    'general.locale': 'tr',
    'general.currency': 'TL',
    'general.createdAt': 'Oluşturulma',
    'general.updatedAt': 'Güncelleme',
    'general.perHour': '/Saat',
    
    // Anasayfa
    'home.mainTitle': 'Öğrenci hayatını kolaylaştıran her şey burada',
    'home.showAllUniversities': 'Tüm üniversiteleri göster',
    'home.allUniversities': 'Tüm Üniversiteler',
    'home.selectUniversity': 'Üniversitenizi seçin...',
    'home.description': 'Kavunla,üniversite öğrencilerinin günlük yaşamlarını kolaylaştırmak için tasarlanmış bir platformudur.',
    'home.exploreCourses': 'Kursları Keşfet',
    'home.howToContinue': 'Nasıl devam etmek istersiniz?',
    'home.continueAsStudent': 'Öğrenci Olarak Devam Et',
    'home.continueAsInstructor': 'Eğitmen Olarak Devam Et',
    'home.loadingUniversities': 'Üniversiteler yükleniyor...',
    // CTA ve kartlar
    'home.cta.exploreResources': 'Kaynakları keşfet',
    'home.cta.exploreProjects': 'Projeleri incele',
    'home.cards.resources.title': 'Kaynaklar',
    'home.cards.resources.subtitle': 'Dökümanları keşfet & paylaş',
    'home.cards.projects.title': 'Projeler',
    'home.cards.projects.subtitle': 'Projelerini sergile, iş birliği yap',
    'home.cards.listings.title': 'İlanlar',
    'home.cards.listings.subtitle': 'Yeni ders ilanlarını keşfet',
    'home.highlights.title': 'Vize-final haftalarında yanındayız',
    'home.highlights.subtitle': 'Kavunla ile sınav döneminde ihtiyacın olan tüm araçlar tek yerde',
    'home.highlights.items.resources.title': 'Kaynak Deposu',
    'home.highlights.items.resources.desc': 'PDF, ders notu ve geçmiş sınavları hızla bul.',
    'home.highlights.items.ai.title': 'AI Çalışma Asistanı',
    'home.highlights.items.ai.desc': 'Sorular hazırla, notlarını özetle, çalışmanı hızlandır.',
    'home.highlights.items.projects.title': 'Gönüllü Projeler',
    'home.highlights.items.projects.desc': 'Deneyim katabileceğin projelere katıl veya kendi ilanını aç.',
    'home.tools.title': 'Hızlı Araçlar',
    'home.tools.subtitle': 'Çalışmana en çok destek olan araçlara tek tıkla ulaş',
    'home.tools.aiNotes': 'Not Çıkart',
    'home.tools.aiQuestions': 'Soru Hazırlat',
    'home.tools.resources': 'Kaynak Bul',
    'home.tools.projects': 'Gönüllü Proje Bul',
    'home.featuredEvents.title': 'Haftanın Etkinlikleri',
    'home.featuredEvents.subtitle': 'Kampüsündeki en güncel etkinlikleri kaçırma',
    'home.featuredEvents.empty': 'Bu hafta öne çıkan etkinlik bulunamadı.',
    'home.featuredEvents.cta': 'Tüm etkinlikleri gör',
    'home.featuredEvents.view': 'Detayları Gör',

    
    // Profil sayfası
    'profile.profileInfo': 'Profil Bilgileri',
    'profile.editProfile': 'Profili Düzenle',
    'profile.fullName': 'Ad Soyad',
    'profile.email': 'E-posta',
    'profile.department': 'Bölüm',
    'profile.class': 'Sınıf',
    'profile.university': 'Üniversite',
    'profile.role': 'Rol',
    
    'profile.updateSuccess': 'Profil başarıyla güncellendi.',
    'profile.accountStatus': 'Hesap Durumu',
    'profile.verified': 'Doğrulanmış',
    'profile.unverified': 'Doğrulanmamış',
    'profile.preparatory': 'Hazırlık',
    'profile.firstYear': '1. Sınıf',
    'profile.secondYear': '2. Sınıf',
    'profile.thirdYear': '3. Sınıf',
    'profile.fourthYear': '4. Sınıf',
    'profile.fifthYear': '5. Sınıf',
    'profile.sixthYear': '6. Sınıf',
    'profile.graduate': 'Mezun',
    
    // Mesajlaşma sayfası
    'messages.myMessages': 'Mesajlarım',
    'messages.conversations': 'Konuşmalarım',
    'messages.searchPlaceholder': 'Ara...',
    'messages.typeMessagePlaceholder': 'Mesajınızı yazın...',
    'messages.startMessaging': 'Mesajlaşmaya Başlayın',
    'messages.selectConversation': 'Sol taraftan bir konuşma seçin veya eğitmen profillerini ziyaret ederek yeni bir mesajlaşma başlatın.',
    'messages.loginRequired': 'Mesajlarınızı görmek için giriş yapmalısınız',
    'messages.noMessages': 'Henüz mesajınız yok',
    'messages.visitInstructors': 'Eğitmenlerle mesajlaşmaya başlamak için profillerini ziyaret edebilirsiniz.',
    'messages.exploreInstructors': 'Eğitmenleri Keşfet',
    'chat.emptyConversation': 'Henüz mesaj yok. Sohbeti başlatmak için bir mesaj gönder!',
    'messages.today': 'Bugün',
    'messages.yesterday': 'Dün',
    
    // İlanlarım sayfası
    'myListings.myListings': 'İlanlarım',
    'myListings.addNewListing': 'Yeni İlan Ekle',
    'myListings.noListingsYet': 'Henüz hiç ilan oluşturmadınız.',
    'myListings.addYourFirstListing': 'İlk İlanınızı Ekleyin',
    'myListings.viewApplications': 'Başvuruları Görüntüle',
    'myListings.deleteConfirmTitle': 'İlanı Silmek İstiyor musunuz?',
    'myListings.deleteConfirmDesc': 'Bu işlem geri alınamaz. Emin misiniz?',
    'myListings.deleteYes': 'Evet, Sil',
    'myListings.deleteNo': 'Hayır',
    'myListings.deleting': 'Siliniyor...',
    
    // Kimlik doğrulama sayfaları
    'auth.login': 'Giriş Yap',
    'auth.register': 'Kayıt Ol',
    'auth.noAccount': 'Hesabınız yok mu?',
    'auth.haveAccount': 'Zaten hesabınız var mı?',
    'auth.email': 'Email',
    'auth.password': 'Şifre',
    'auth.rememberMe': 'Beni Hatırla',
    'auth.forgotPassword': 'Şifremi Unuttum',
    'auth.fullName': 'Ad Soyad',
    'auth.confirmPassword': 'Şifre Tekrar',
    'auth.role': 'Rol',
    'auth.student': 'Öğrenci',
    'auth.instructor': 'Eğitmen',
    'auth.university': 'Üniversite',

    // Eğitmenler sayfası
    'instructors.title': 'Eğitmenlerimiz',
    'instructors.universityDesc': '{university} üniversitesindeki eğitmenlerimizle tanışın ve ihtiyacınıza en uygun eğitmeni seçin.',
    'instructors.generalDesc': 'Alanında uzman eğitmenlerimizle tanışın ve ihtiyacınıza en uygun eğitmeni seçin.',
    'instructors.searchPlaceholder': 'Eğitmen ara...',
    'instructors.departmentsTitle': 'Uzmanlık Alanları',
    'instructors.noMatch': 'Aradığınız kriterlere uygun eğitmen bulunamadı.',
    'instructors.noInstructors': 'Henüz hiç eğitmen bulunmuyor.',
    'instructors.tryDifferentSearch': 'Farklı arama kriterleri deneyebilirsiniz.',
    'instructors.role': 'Eğitmen',
    'instructors.generalInstructor': 'Genel Eğitmen',
    'instructors.experience': '3+ Yıl Deneyim',
    'instructors.rating': '4.8/5 Puan',
    'instructors.expertise': 'Genel Eğitmen',

    // Bölüm isimleri
    'departments.computer': 'Bilgisayar Mühendisliği',
    'departments.dentistry': 'Diş Hekimliği',
    'departments.medicine': 'Tıp',
    'departments.law': 'Hukuk',
    'departments.mechanical': 'Makine Mühendisliği',
    'departments.electrical': 'Elektrik-Elektronik Mühendisliği',
    'departments.business': 'İşletme',
    'departments.psychology': 'Psikoloji',
    'departments.architecture': 'Mimarlık',
    'departments.industrial': 'Endüstri Mühendisliği',
    'departments.civil': 'İnşaat Mühendisliği',
    'departments.software': 'Yazılım Mühendisliği',
    'general.allDepartments': 'Tüm Bölümler',
    'general.allRatings': 'Tüm Puanlar',
    'auth.selectUniversity': 'Üniversitenizi seçin...',
    'auth.department': 'Bölümünüz',
    'auth.departmentPlaceholder': 'Bölümünüzü yazınız...',
    'auth.class': 'Sınıfınız',
    'auth.selectClass': 'Seçiniz',
    'auth.passwordRequirement': 'En az 8 karakter olmalıdır',
    'auth.loggingIn': 'Giriş Yapılıyor...',
    'auth.registering': 'Kayıt Yapılıyor...',
    'auth.otherSignInOptions': 'Diğer giriş seçenekleri',
    'auth.termsAgreement': 'Kayıt olarak, kabul etmiş sayılırsınız:',
    'auth.termsOfUse': 'Kullanım Koşulları',
    'auth.and': 've',
    'auth.privacyPolicy': 'Gizlilik Politikası',
    
    // Derslerim sayfası
    'lessons.myLessons': 'Derslerim',
    'lessons.teacherManageLessons': 'Tüm derslerinizi bu sayfadan yönetebilirsiniz.',
    'lessons.studentViewLessons': 'Kayıtlı olduğunuz tüm dersleri bu sayfadan görüntüleyebilirsiniz.',
    'lessons.totalLessons': 'Toplam Ders',
    'lessons.plannedLessons': 'Planlanan Dersler',
    'lessons.completedLessons': 'Tamamlanan Dersler',
    'lessons.cancelledLessons': 'İptal Edilen Dersler',
    'lessons.lessonCalendar': 'Ders Takvimi',
    'lessons.status': 'Durum',
    'lessons.start': 'Başlangıç',
    'lessons.end': 'Bitiş',
    'lessons.student': 'Öğrenci',
    'lessons.instructor': 'Eğitmen',
    'lessons.price': 'Ücret',
    'lessons.completeLesson': 'Dersi Tamamla',
    'lessons.cancelLesson': 'Dersi İptal Et',
    'lessons.viewLessonDetails': 'Ders Detaylarını Görüntüle',
    'lessons.statusOpen': 'Açık',
    'lessons.statusScheduled': 'Planlandı',
    'lessons.statusCompleted': 'Tamamlandı',
    'lessons.statusCancelled': 'İptal Edildi',
    'lessons.details': 'Ders Detayları',
    'lessons.createdAt': 'Oluşturulma Tarihi',
    'lessons.minute': 'dakika',
    'lessons.noDate': 'Tarih belirtilmemiş',
    'lessons.notFound': 'Ders Bulunamadı',
    'lessons.notFoundDesc': 'Görüntülemeye çalıştığınız ders bulunamadı veya erişim izniniz yok.',
    'lessons.completedAt': 'Tamamlandı',
    'lessons.studentInfo': 'Öğrenci Bilgileri',
    'lessons.teacherInfo': 'Eğitmen Bilgileri',
    'lessons.paymentStatus': 'Ödeme Durumu',
    'lessons.notPaid': 'Bu ders için henüz ödeme yapılmamış.',
    'lessons.payNow': 'Ödeme Yap',
    'lessons.paid': 'Ödeme tamamlandı',
    'messages.sendMessage': 'Mesaj Gönder',
    'lessons.student ': 'Öğrenci',
    'lessons.teacher': 'Eğitmen',
    'general.noName': 'İsim belirtilmemiş',
    'general.noEmail': 'E-posta belirtilmemiş',

    // Proje oluştur
    'project.createNewTitle': 'Yeni Proje Oluştur',
    'project.title': 'Proje Adı',
    'project.description': 'Açıklama',
    'project.linkedinUrlOptional': 'LinkedIn URL (opsiyonel)',
    'project.contactPlaceholder': 'İletişim (e-posta, Discord vs.)',
    'project.applicantRequirements': 'Başvuranın Gereksinimleri',
    'project.benefitsPlaceholder': 'Başvurana Sağlayacaklarımız',
    'project.create': 'Oluştur',
    'project.creating': 'Kaydediliyor...',

    // Loglar ve hatalar
    'logs.userNotLoggedIn': 'Kullanıcı girişi yapılmamış, yönlendiriliyor...',
    'logs.listingCreationError': 'İlan oluşturulurken hata:',
    'logs.previewUpdateError': 'Önizleme sayısı güncellenirken hata oluştu',
    'logs.fetchingLessonStats': 'Kullanıcı girişi yapılmış, ders istatistikleri getiriliyor...',
    'logs.sendingApiRequest': 'API isteği gönderiliyor:',
    'logs.tokenAvailable': 'Token mevcut:',
    'logs.lessonStatsReceived': 'Ders istatistikleri alındı:',
    'errors.userInfoNotFound': 'Kullanıcı bilgisi bulunamadı',
    'errors.apiError': 'API hatası:',
    'errors.errorDetails': 'Hata detayı:',
    'errors.fetchingLessonStats': 'Ders istatistikleri alınırken bir hata oluştu',
    'errors.fetchingLessonStatsError': 'Ders istatistikleri getirme hatası:',
    'errors.serverError': 'Sunucu hatası',
    'errors.universityNotFound': 'Üniversite bilgisi bulunamadı',
    'errors.fetchingListings': 'İlanlar getirilirken bir hata oluştu',
    'errors.tokenNotFound': 'Token bulunamadı',
    'errors.sessionExpired': 'Oturumunuz sonlanmış görünüyor. Lütfen tekrar giriş yapın.',
    'errors.unknownError': 'Bilinmeyen hata',
    'errors.httpError': 'HTTP hata: {status}',
    'errors.loadingConversations': 'Konuşmalar yüklenirken hata oluştu',
    'errors.loadingConversationsDetail': 'Konuşmalar yüklenirken bir hata oluştu:',
    'errors.fetchingUserDetails': 'Kullanıcı detayları alınırken hata oluştu',
    'errors.titleRequired': 'Lütfen bir başlık girin',
    'errors.descriptionRequired': 'Lütfen bir açıklama girin',
    'errors.priceRequired': 'Lütfen ücret bilgisi girin',
    'errors.durationRequired': 'Lütfen süre bilgisi girin',
    'errors.userIdNotFound': 'Kullanıcı kimliği bulunamadı. Lütfen tekrar giriş yapın.',
    'errors.sessionNotFound': 'Oturum bilgisi bulunamadı. Lütfen tekrar giriş yapın.',
    'errors.listingCreationError': 'İlan oluşturulurken bir hata oluştu',
    'errors.listingCreationErrorTryAgain': 'İlan oluşturulurken bir hata oluştu. Lütfen daha sonra tekrar deneyin.',
    'errors.loginRequired': 'Bu kaynağı indirebilmek için giriş yapmalısınız.',
    'errors.noDownloadPermission': 'Bu kaynağı indirmek için yetkiniz bulunmamaktadır.',
    'errors.invalidUniversity': 'Lütfen geçerli bir üniversite seçin',
    'errors.invalidDepartment': 'Lütfen geçerli bir bölüm seçin',
    'errors.invalidLinkedInUrl': 'LinkedIn URL geçersiz',
    'errors.prohibitedContentDetected': 'Uygunsuz içerik tespit edildi. Lütfen metni düzenleyin.',
    'errors.projectCreationFailed': 'Proje oluşturulamadı',
    'errors.courseRequired': 'Lütfen ders adını girin',
    
    // Footer
    'footer.platformDescription': 'Kavunla, öğrencileri eğitmenlerle buluşturan ve eğitimin geleceğini şekillendiren platform.',
    'footer.quickLinks': 'Hızlı Bağlantılar',
    'footer.legal': 'Yasal',
    'footer.termsOfUse': 'Kullanım Koşulları',
    'footer.privacyPolicy': 'Gizlilik Politikası',
    'footer.cookiePolicy': 'Çerez Politikası',
    'footer.pdpl': 'KVKK',
    'footer.contact': 'İletişim',
    'footer.allRightsReserved': 'Tüm hakları saklıdır.',
    'footer.support': 'Destek',
    'footer.security': 'Güvenlik',
    'footer.notification': 'Bildirim',

  },
  en: {
    'nav.eventsAdmin': 'Events',
    'nav.language': 'Language',
    'nav.mainMenu': 'Main Menu',
    'nav.account': 'My Account',
    'nav.openMenu': 'Open menu',
    'nav.closeMenu': 'Close menu',
    'nav.comingSoon': 'Coming soon',
    'nav.aiAssistant': 'Question Generator',
    'nav.aiNotes': 'Take Notes',
    'events.title': 'Events',
    'events.subtitle': 'Discover and filter all club events.',

    'events.searchPlaceholder': 'Search events or keywords',
    'events.searchButton': 'Search',
    'events.filtersTitle': 'Filters',
    'events.filterLocation': 'Location',
    'events.allLocations': 'All Locations',
    'events.filterUniversity': 'University',
    'events.filterClub': 'Club',
    'events.filterCategory': 'Category',
    'events.filterDateFrom': 'Start Date',
    'events.filterDateTo': 'End Date',
    'events.resetFilters': 'Reset Filters',
    'events.noResults': 'No events match your filters.',
    'events.allUniversities': 'All Universities',
    'events.allClubs': 'All Clubs',
    'events.allCategories': 'All Categories',
    'events.eventDate': 'Date',
    'events.locationLabel': 'Location',
    'events.resourcesLabel': 'Resources',
    'events.associatedClubs': 'Associated Clubs',
    'events.detail.back': 'Back to events',
    'events.detail.organizedBy': 'Organized by',
    'events.detail.universities': 'Universities',
    'events.detail.resourcesTitle': 'Event Resources',
    'events.detail.resourcesEmpty': 'No resources have been shared for this event yet.',
    'events.detail.clubsTitle': 'Associated Clubs',
    'events.detail.clubsEmpty': 'There are no clubs linked to this event yet.',
    'events.detail.loading': 'Loading event...',
    'events.detail.error': 'An error occurred while loading the event.',
    'events.detail.notFound': 'Event not found.',
    'events.admin.loginTitle': 'Event Management Login',
    'events.admin.emailLabel': 'Admin Email',
    'events.admin.emailPlaceholder': 'e.g. etkinlikkavunla',
    'events.admin.passwordLabel': 'Admin Password',
    'events.admin.passwordPlaceholder': 'Enter your password',
    'events.admin.loggingIn': 'Logging in...',
    'events.admin.loginButton': 'Login',
    'events.admin.loginError': 'Login failed. Please check your credentials.',
    'events.admin.loginSuccess': 'Login successful',
    'events.admin.addTitle': 'Add Event',
    'events.admin.listTitle': 'Events',
    'events.admin.manageDescription': 'Manage, edit or delete events.',
    'events.admin.addNewButton': 'Add Event',
    'events.admin.logoutButton': 'Logout',
    'events.admin.titleLabel': 'Event Title',
    'events.admin.dateLabel': 'Event Date & Time',
    'events.admin.categoryLabel': 'Category',
    'events.admin.locationLabel': 'Location',
    'events.admin.photoLabel': 'Photo',
    'events.admin.descriptionLabel': 'Description',
    'events.admin.resourcesLabel': 'Resources / Links',
    'events.admin.resourcesHint': 'Add one link per line.',
    'events.admin.resourcesPlaceholder': 'https://...',
    'events.admin.tableDate': 'Date',
    'events.admin.tableCategory': 'Category',
    'events.admin.tableLocation': 'Location',
    'events.admin.tableActions': 'Actions',
    'events.admin.editButton': 'Edit',
    'events.admin.deleteButton': 'Delete',
    'events.admin.deleteConfirm': 'Are you sure you want to delete this event?',
    'events.admin.deleteSuccess': 'Event deleted successfully.',
    'events.admin.deleteError': 'Failed to delete event.',
    'events.admin.updateSuccess': 'Event updated successfully.',
    'events.admin.updateError': 'Failed to update event.',
    'events.admin.noEvents': 'No events found.',
    'events.admin.editTitle': 'Edit Event',
    'events.admin.closeButton': 'Close',
    'events.admin.saveChangesButton': 'Save Changes',
    'events.admin.clubSelectTitle': 'Select Clubs',
    'events.admin.loadingClubs': 'Loading clubs...',
    'events.admin.noClubs': 'No clubs found.',
    'events.admin.loadClubsError': 'An error occurred while loading clubs.',
    'events.admin.dateRequired': 'Please select an event date.',
    'events.admin.selectClubError': 'Select at least one club.',
    'events.admin.createSuccess': 'Event created successfully.',
    'events.admin.createError': 'Failed to create event.',
    'events.admin.saving': 'Saving...',
    'events.admin.saveButton': 'Save Event',
    'ai.question.description': 'Upload PDFs, text or images and automatically generate exam, open-ended or short-answer questions. Once the OpenAI integration is ready, results will be produced instantly.',
    'ai.question.uploadLabel': 'Upload study material',
    'ai.question.uploadHint': 'Select PDF, DOCX, TXT or image files',
    'ai.question.uploadSubHint': 'Drag and drop or click to upload (max 15MB)',
    'ai.question.notesLabel': 'Additional notes (optional)',
    'ai.question.notesPlaceholder': 'E.g. Generate 5 multiple-choice questions with medium Bloom taxonomy difficulty.',
    'ai.question.countLabel': 'Question count',
    'ai.question.typeLabel': 'Question type',
    'ai.question.typeMultipleChoice': 'Multiple choice',
    'ai.question.typeOpenEnded': 'Open-ended',
    'ai.question.choiceCountLabel': 'Number of choices',
    'ai.question.generateButton': 'Generate Questions',
    'ai.question.generating': 'Generating...',
    'ai.question.howItWorksTitle': 'How it works',
    'ai.question.howItWorksDescription': 'When an OpenAI API key is provided, the uploaded material will be analysed and questions matching your criteria will appear here.',
    'ai.question.tipTitle': 'Tip',
    'ai.question.tipLine1': 'You can upload PDFs, lecture notes or images at once.',
    'ai.question.tipLine2': 'Use the notes field to specify question types, grade level or topic.',
    'ai.question.tipLine3': 'After integration, all results can be stored in JSON format.',
    'ai.question.resultsTitle': 'Generated Questions',
    'ai.question.resultsPlaceholder': 'Once OpenAI is connected, generated questions will be listed here. For now the interface is ready.',
    'ai.question.answerKeyTitle': 'Answer Key',
    'ai.question.answerKeyShow': 'Show Key',
    'ai.question.answerKeyHide': 'Hide Key',
    'ai.question.answerUnavailable': 'Answer not provided.',
    'ai.question.textLabel': 'Paste text (optional)',
    'ai.question.textPlaceholder': 'E.g. copy the relevant part of your lecture notes here.',
    'ai.summary.description': 'Upload PDF, text or visual lesson materials and turn them into concise study notes within minutes.',
    'ai.summary.uploadLabel': 'Upload lesson material',
    'ai.summary.uploadHint': 'Select PDF, DOCX, TXT or image files',
    'ai.summary.uploadSubHint': 'Drag and drop or click to upload (max 15MB)',
    'ai.summary.notesLabel': 'Topics to emphasise (optional)',
    'ai.summary.notesPlaceholder': 'E.g. highlight key concepts, historical timeline, numeric results.',
    'ai.summary.toneLabel': 'Note style',
    'ai.summary.toneAcademic': 'Academic',
    'ai.summary.toneSimple': 'Plain',
    'ai.summary.generateButton': 'Generate Notes',
    'ai.summary.generating': 'Preparing notes...',
    'ai.summary.howItWorksTitle': 'How it works',
    'ai.summary.howItWorksDescription': 'Your content is analysed and turned into student-friendly notes in the tone you select.',
    'ai.summary.tipTitle': 'Tip',
    'ai.summary.tipLine1': 'Plain style is great for quick revision sheets.',
    'ai.summary.tipLine2': 'Academic style suits detailed or formal study materials.',
    'ai.summary.tipLine3': 'Use the extra notes field to specify exam scope or desired length.',
    'ai.summary.resultsTitle': 'Generated Notes',
    'ai.summary.resultsPlaceholder': 'No notes yet. Upload some content to generate study notes.',
    'ai.summary.textLabel': 'Paste text (optional)',
    'ai.summary.textPlaceholder': 'E.g. paste the important parts of your course here.',
    'ai.common.fileSelected': 'Selected file',
    'ai.common.removeFile': 'Remove file',
    'ai.common.noFileSelected': 'No file selected yet',
    'ai.common.missingSource': 'Please upload a file or provide text.',
    'ai.common.unexpectedError': 'An unexpected error occurred. Please try again.',
    'ai.common.apiError': 'An error occurred while processing: {{message}}',
    'nav.notifications': 'Notifications',
    'notifications.all': 'All Notifications',
    'notifications.unread': 'Unread Notifications',
    'notifications.read': 'Read Notifications',
    'notifications.noNotifications': 'No notifications found',
    'notifications.markAsRead': 'Mark as read',
    'notifications.markAsUnread': 'Mark as unread',
    'notifications.delete': 'Delete',
    'notifications.deleteConfirm': 'Are you sure you want to delete this notification?',
    'notifications.deleteSuccess': 'Notification deleted',
    'notifications.deleteError': 'Error deleting notification',
    'notifications.loading': 'Loading notifications...',
    'notifications.error': 'Error loading notifications',
    'notifications.empty': 'You have no notifications yet',
    'notifications.loginRequired': 'You need to log in to view notifications',
    'notifications.goToLogin': 'Log In',
    'notifications.markAllAsRead': 'Mark All as Read',
    'notifications.markAllAsReadSuccess': 'All notifications marked as read',
    'notifications.markAllAsReadError': 'Error marking notifications as read',
    'notifications.timeAgo.minutes': '{count} minutes ago',
    'notifications.timeAgo.hours': '{count} hours ago', 
    'notifications.timeAgo.days': '{count} days ago',
    
    // General
    'notifications.viewDetails': 'View Details',
    'home.description': 'Kavunla is a next-generation education platform that brings together students from the same university.',
    'general.search': 'Search',
    'general.filter': 'Filter',
    'general.filters': 'Filters',
    'general.searchResources': 'Search Resources',
    'general.filterResources': 'Filter Resources',
    'general.allResources': 'All Resources',
    'general.allUniversities': 'All Universities',
    'general.shareResource': 'Share Resource',
    'general.resourceTitle': 'Resource Title',
    'general.resourceDescription': 'Resource Description',
    'general.resourceType': 'Resource Type',
    'general.resourceLink': 'Resource Link',
    'general.resourceFile': 'Resource File',
    'general.uploadResource': 'Upload Resource',
    'general.resourceCategory': 'Category',
    'general.resourceSubject': 'Subject',
    'general.course': 'Course',
    'general.coursePlaceholder': 'e.g. Mathematics I / Calculus',
    'general.resourceLevel': 'Level',
    'general.resourceLanguage': 'Language',
    'general.resourceFormat': 'Format',
    'general.fileUploadClickOrDrag': 'Click or drag to upload file',
    'general.fileUploadFormats': 'Supported formats: PDF, DOC, PPT, XLS, MP4, MP3, JPG, PNG (Max 50MB)',
    'general.fileSelected': 'File selected',
    'general.noFileSelected': 'No file selected',
    'general.tagsPlaceholder': 'matematik, calculus, türev, integral',
    'general.resourceAuthor': 'Author',
    'general.resourceDate': 'Date',
    'general.resourceSize': 'Size',
    'general.resourceDownload': 'Download',
    'general.resourceView': 'View',
    'general.resourceShare': 'Share',
    'general.resourceSave': 'Save',
    'general.resourceDelete': 'Delete',
    'general.resourceEdit': 'Edit',
    'general.resourceReport': 'Report',
    'general.resourceLike': 'Like',
    'general.resourceComment': 'Comment',
    'general.resourceComments': 'Comments',
    'general.resourceRating': 'Rating',
    'general.resourceViews': 'Views',
    'general.resourceDownloads': 'Downloads',
    'general.resourceShares': 'Shares',
    'general.resourceLikes': 'Likes',
    'general.resourceDislikes': 'Dislikes',
    'general.resourceFavorites': 'Favorites',
    'general.resourceBookmarks': 'Bookmarks',
    'general.preview': 'Preview',
    'general.downloadFile': 'Download File',
    'general.resourceRelated': 'Related Resources',
    'general.resourcePopular': 'Popular Resources',
    'general.resourceRecent': 'Recent Resources',
    'general.resourceFeatured': 'Featured Resources',
    'general.resourceRecommended': 'Recommended Resources',
    'general.resourceTrending': 'Trending Resources',
    'general.resourceNew': 'New Resources',
    'general.resourceMostViewed': 'Most Viewed',
    'general.resourceMostDownloaded': 'Most Downloaded',
    'general.resourceMostShared': 'Most Shared',
    'general.resourceMostLiked': 'Most Liked',
    'general.resourceMostCommented': 'Most Commented',
    'general.resourceMostRated': 'Most Rated',
    'general.resourceHighestRated': 'Highest Rated',
    'general.resourceLowestRated': 'Lowest Rated',
    'general.resourceCategories': 'Categories',
    'general.resourceSubjects': 'Subjects',
    'general.resourceLevels': 'Levels',
    'general.resourceLanguages': 'Languages',
    'general.resourceFormats': 'Formats',
    'general.resourceAuthors': 'Authors',
    'general.resourceDates': 'Dates',
    'general.resourceSizes': 'Sizes',
    'general.resourceTags': 'Tags',
    'general.resourceKeywords': 'Keywords',
    'general.resourceSearch': 'Resource Search',
    'general.resourceAdvancedSearch': 'Advanced Search',
    'general.resourceSearchResults': 'Search Results',
    'general.resourceSearchNoResults': 'Resource Not Found',
    'general.resourceSearchTips': 'Search Tips',
    'general.resourceSearchFilters': 'Search Filters',
    'general.resourceSearchSort': 'Sort',
    'general.resourceSearchSortBy': 'Sort By',
    'general.resourceSearchSortOrder': 'Sort Order',
    'general.resourceSearchSortAsc': 'Ascending',
    'general.resourceSearchSortDesc': 'Descending',
    'general.price': 'Price',
    'general.duration': 'Duration',
    'general.method': 'Method',
    'general.submit': 'Submit',
    'general.cancel': 'Cancel',
    'general.save': 'Save',
    'general.edit': 'Edit',
    'general.delete': 'Delete',
    'general.back': 'Back',
    'general.next': 'Next',
    'general.finish': 'Finish',
    'general.loading': 'Loading...',
    'general.error': 'Error',
    'general.success': 'Success',
    'general.noResults': 'No results found',
    'general.clearFilters': 'Clear Filters',
    'general.showAll': 'Show All',
    'general.showFavorites': 'Show Favorites',
    'general.hourlyRate': 'Hourly Rate',
    'general.priceLabel': 'Price',
    'general.methodLabel': 'Method',
    'general.frequencyLabel': 'Frequency',
    'general.instructorFromLabel': 'Instructor Received From',
    'general.lessonFrequency': 'Lesson Frequency',
    'frequency.daily': 'Daily',
    'frequency.weekly': 'Weekly',
    'frequency.monthly': 'Monthly',
    'frequency.flexible': 'Flexible',
    'general.lessonMethod': 'Lesson Method',
    'general.instructor': 'Instructor',
    'general.university': 'University',
    'general.department': 'Department',
    'general.academicLevel': 'Academic Level',
    'general.expertise': 'Expertise',
    'general.description': 'Description',
    'general.contactTeacher': 'Contact Teacher',
    'general.bookAppointment': 'Book Appointment',
    'general.sendMessage': 'Send Message',
    'general.sendEmail': 'Send Email',
    'general.goBack': 'Go Back',
    'general.backToListings': 'Back to Listings',
    'general.openListings': 'Open Listings',
    'general.showAllListings': 'Show All Listings',
    'general.processing': 'Processing...',
    'general.publish': 'Publish',
    'general.accessDenied': 'Access Denied',
    'general.accessDeniedMessage': 'You need to login with an instructor account to access this page.',
    'general.goToHomepage': 'Go to Homepage',
    'general.online': 'Online',
    'general.faceToFace': 'Face to Face',
    'general.hybrid': 'Hybrid (Online + Face to Face)',
    'general.createListingTitle': 'Create New Listing',
    'listings.universityListings': 'University Listings',
    'listings.exploreTeacherLessons': 'Explore Teacher Lessons',
    'general.listingTitle': 'Listing Title',
    'general.listingTitlePlaceholder': 'E.g.: Python Programming Course',
    'general.listingDescription': 'Listing Description',
    'general.listingDescriptionPlaceholder': 'Provide information about the course content and yourself...',
    'general.hourlyPrice': 'Lesson Price (₺/Hour)',
    'general.hours': 'Hours',
    'general.lessonDurationHours': 'Lesson Duration (Hours)',
    'general.hourlyPricePlaceholder': 'E.g.: 20',
    'general.instructorFrom': 'Instructor You Take Lessons From',
    'general.instructorFromPlaceholder': 'E.g.: Ankara University, Prof. Dr. Ahmet Yilmaz',
    'general.publishListing': 'Publish Listing',
    'general.listingCreated': 'Your listing has been created successfully!',
    'general.searchPlaceholder': 'Search listings...',
    'general.filterOptions': 'Filter Options',
    'general.sort': 'Sort',
    'general.newest': 'Newest',
    'general.oldest': 'Oldest',
    'general.priceAsc': 'Price (Ascending)',
    'general.priceDesc': 'Price (Descending)',
    'general.minPrice': 'Minimum Price (₺)',
    'general.maxPrice': 'Maximum Price (₺)',
    'general.allMethods': 'All methods',
    'general.minPricePlaceholder': 'Minimum price',
    'general.maxPricePlaceholder': 'Maximum price',
    'general.resultsFound': 'listings found',
    'general.notSpecified': 'Not Specified',
    'general.unknown': 'Unknown',
    'general.noResultsFound': 'No Search Results Found',
    'general.noResultsForSearch': 'No results found for your search criteria.',
    'general. resourceSearchNoResults': 'Resource Not Found',
    'general.downloadStarted': 'Download started.',
    'general.downloadError': 'An error occurred during download. Please try again.',
    'general.fileNotFound': 'File not found. There is no downloadable file for this resource.',
    'general.clubName': 'Club Name',
    'general.clubCategory': 'Club Category',
    'general.noClubsYet': 'You don\'t have any clubs yet.',
    'general.addYourFirstClub': 'Create your first club',
    'general.clubDescription': 'Club Description',
    'general.clubUniversity': 'University',
    'general.clubCreate': 'Create Club',
    'general.clubUpdate': 'Update Club',
    'general.clubDelete': 'Delete Club',
    'general.clubSave': 'Save',
    'general.clubCancel': 'Cancel',
    'general.clubNameRequired': 'Club name is required',
    'general.clubCreated': 'Club created successfully!',
    'general.clubUpdated': 'Club updated successfully!',
    'general.clubDeleted': 'Club deleted successfully!',
    'general.clubSearch': 'Search clubs...',
    'general.clubSearchPlaceholder': 'Search club name or category...',
    'general.clubCategoryAll': 'All Categories',
    'general.clubUniversityAll': 'All Universities',
    'general.clubNoResults': 'No clubs found matching your criteria.',
    'general.clubAdd': 'Add Club',
    'general.clubJoin': 'Join',
    'general.clubLeave': 'Leave',
    'general.clubMembers': 'Members',
    'general.clubOwner': 'Owner',
    'general.clubDetails': 'Club Details',
    'general.clubContact': 'Contact',
    'general.clubActivities': 'Activities',
    'general.clubAnnouncements': 'Announcements',
    'general.clubEvents': 'Events',
    'general.clubPhotos': 'Photos',
    'general.clubDocuments': 'Documents',
    'general.clubDiscussions': 'Discussions',
    'general.clubSettings': 'Settings',
    'general.clubEdit': 'Edit Club',
    'general.clubDeleteConfirm': 'Are you sure you want to delete this club?',
    'general.clubDeleteConfirmDesc': 'This action cannot be undone.',
    'general.clubDeleteYes': 'Yes, Delete',
    'general.clubDeleteNo': 'No',
    'general.tryAgain': 'Try Again',
    'general.listingDetails': 'Listing Details',
    'general.lessonDetails': 'Lesson Details',
    'general.teacherInfo': 'Teacher Information',
    'general.additionalInfo': 'Additional Information',
    'general.allListings': 'All Listings',
    'general.hour': 'Hour',
    'general.postDate': 'Post Date',
    'general.viewDetails': 'View Details',
    'general.locale': 'en',
    'general.currency': 'Turkish Lira',
    'general.createdAt': 'Created at',
    'general.updatedAt': 'Updated at',
    'general.perHour': 'Per Hour',
    
    // Homepage (moved to the top EN block)
    
    // Profile page
    'profile.profileInfo': 'Profile Information',
    'profile.editProfile': 'Edit Profile',
    'profile.fullName': 'Full Name',
    'profile.email': 'Email',
    'profile.university': 'University',
    'profile.role': 'Role',
    'profile.department': 'Department',
    'profile.class': 'Class',
    'profile.updateSuccess': 'Profile updated successfully.',
    'profile.accountStatus': 'Account Status',
    'profile.verified': 'Verified',
    'profile.unverified': 'Unverified',
    'profile.preparatory': 'Preparatory',
    'profile.firstYear': '1st Year',
    'profile.secondYear': '2nd Year',
    'profile.thirdYear': '3rd Year',
    'profile.fourthYear': '4th Year',
    'profile.fifthYear': '5th Year',
    'profile.sixthYear': '6th Year',
    'profile.graduate': 'Graduate',
    
    // Messages page
    'messages.myMessages': 'My Messages',
    'messages.conversations': 'My Conversations',
    'messages.searchPlaceholder': 'Search...',
    'messages.typeMessagePlaceholder': 'Type your message...',
    'messages.startMessaging': 'Start Messaging',
    'messages.selectConversation': 'Select a conversation from the left or visit instructor profiles to start a new conversation.',
    'messages.loginRequired': 'You need to log in to view your messages',
    'messages.noMessages': 'You don\'t have any messages yet',
    'messages.visitInstructors': 'You can visit instructor profiles to start messaging with them.',
    'messages.exploreInstructors': 'Explore Instructors',
    'chat.emptyConversation': 'No messages yet. Send a message to start the conversation!',
    
    // My Listings page
    'myListings.myListings': 'My Listings',
    'myListings.addNewListing': 'Add New Listing',
    'myListings.noListingsYet': 'You haven\'t created any listings yet.',
    'myListings.addYourFirstListing': 'Add Your First Listing',
    'myListings.viewApplications': 'View Applications',
    'myListings.deleteConfirmTitle': 'Do you want to delete this listing?',
    'myListings.deleteConfirmDesc': 'This action cannot be undone. Are you sure?',
    'myListings.deleteYes': 'Yes, Delete',
    'myListings.deleteNo': 'No',
    'myListings.deleting': 'Deleting...',
    
    // Authentication pages
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.haveAccount': 'Already have an account?',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.rememberMe': 'Remember me',
    'auth.forgotPassword': 'Forgot password',
    'auth.fullName': 'Full Name',
    'auth.confirmPassword': 'Confirm Password',
    'auth.role': 'Role',
    'auth.student': 'Student',
    'auth.instructor': 'Instructor',
    'auth.university': 'University',
    'auth.selectUniversity': 'Select your university...',
    'auth.department': 'Department',
    'auth.departmentPlaceholder': 'Enter your department...',
    'auth.class': 'Class',
    'auth.selectClass': 'Select',
    'auth.passwordRequirement': 'Must be at least 8 characters',
    'auth.loggingIn': 'Logging in...',
    'auth.registering': 'Registering...',
    'auth.otherSignInOptions': 'Other sign in options',
    'auth.termsAgreement': 'By signing up, you agree to our',
    'auth.termsOfUse': 'Terms of Use',
    'auth.and': 'and',
    'auth.privacyPolicy': 'Privacy Policy',
    'auth.loginError': 'Error occurred during login',
    'auth.registrationError': 'Error occurred during registration',
    'auth.passwordsDoNotMatch': 'Passwords do not match',
    'auth.loadingUniversities': 'Error loading universities',
    'auth.loadingConversations': 'Error loading conversations',
    'auth.loadingConversationsDetail': 'An error occurred while loading conversations:',
    'auth.fetchingUserDetails': 'Error fetching user details',
    'auth.titleRequired': 'Please enter a title',
    'auth.descriptionRequired': 'Please enter a description',
    
    // My Lessons page
    'lessons.myLessons': 'My Lessons',
    'lessons.teacherManageLessons': 'You can manage all your lessons from this page.',
    'lessons.studentViewLessons': 'You can view all the lessons you are registered for from this page.',
    'lessons.totalLessons': 'Total Lessons',
    'lessons.plannedLessons': 'Planned Lessons',
    'lessons.completedLessons': 'Completed Lessons',
    'lessons.cancelledLessons': 'Cancelled Lessons',
    'lessons.lessonCalendar': 'Lesson Calendar',
    'lessons.status': 'Status',
    'lessons.start': 'Start',
    'lessons.end': 'End',
    'lessons.student': 'Student',
    'lessons.instructor': 'Instructor',
    'lessons.price': 'Price',
    'lessons.completeLesson': 'Complete Lesson',
    'lessons.cancelLesson': 'Cancel Lesson',
    'lessons.viewLessonDetails': 'View Lesson Details',
    'lessons.statusOpen': 'Open',
    'lessons.statusScheduled': 'Scheduled',
    'lessons.statusCompleted': 'Completed',
    'lessons.statusCancelled': 'Cancelled',
    'lessons.details': 'Lesson Details',
    'lessons.createdAt': 'Created At',
    'lessons.minute': 'minute',
    'lessons.noDate': 'No date specified',
    'lessons.notFound': 'Lesson Not Found',
    'lessons.notFoundDesc': 'The lesson you are trying to view was not found or you do not have access.',
    'lessons.completedAt': 'Completed',
    'lessons.studentInfo': 'Student Information',
    'lessons.teacherInfo': 'Instructor Information',
    'lessons.paymentStatus': 'Payment Status',
    'lessons.notPaid': 'Payment has not been made for this lesson yet.',
    'lessons.payNow': 'Pay Now',
    'lessons.paid': 'Payment completed',
    'messages.sendMessage': 'Send Message',
    'messages.today': 'Today',
    'messages.yesterday': 'Yesterday',
    'lessons.student ': 'Student',
    'lessons.teacher': 'Instructor',
    'general.noName': 'No name specified',
    'general.noEmail': 'No email specified',
    'clubs.title': 'Clubs',
    'clubs.addClub': 'Add Club',
    'clubs.searchPlaceholder': 'Search (name, kind)',
    'clubs.categoryAll': 'Category (All)',
    'clubs.universityAll': 'University (All)',
    'clubs.contactButton': 'Contact',
    'clubs.about': 'About',
    'clubs.category.general': 'General',
    'clubs.category.web': 'Web',
    'clubs.category.mobile': 'Mobile',
    'clubs.category.desktop': 'Desktop',
    'clubs.category.ai': 'Artificial Intelligence',
    'clubs.category.game': 'Game',
    'clubs.category.dataScience': 'Data Science',
    'clubs.category.cyberSecurity': 'Cyber Security',
    'clubs.category.other': 'Other',

    // Logs and errors
    'logs.userNotLoggedIn': 'User not logged in, redirecting...',
    'logs.listingCreationError': 'Error creating listing:',
    'logs.previewUpdateError': 'An error occurred while updating preview count',
    'logs.fetchingLessonStats': 'User logged in, fetching lesson statistics...',
    'logs.sendingApiRequest': 'Sending API request:',
    'logs.tokenAvailable': 'Token available:',
    'logs.lessonStatsReceived': 'Lesson statistics received:',
    'errors.userInfoNotFound': 'User information not found',
    'errors.apiError': 'API error:',
    'errors.errorDetails': 'Error details:',
    'errors.fetchingLessonStats': 'An error occurred while fetching lesson statistics',
    'errors.fetchingLessonStatsError': 'Error fetching lesson statistics:',
    'errors.serverError': 'Server error',
    'errors.universityNotFound': 'University information not found',
    'errors.fetchingListings': 'Error fetching listings',
    'errors.tokenNotFound': 'Token not found',
    'errors.sessionExpired': 'Your session appears to have expired. Please log in again.',
    'errors.unknownError': 'Unknown error',
    'errors.httpError': 'HTTP error: {status}',
    'errors.loginError': 'Error occurred during login',
    'errors.registrationError': 'Error occurred during registration',
    'errors.passwordsDoNotMatch': 'Passwords do not match',
    'errors.loadingUniversities': 'Error loading universities',
    'errors.loadingConversations': 'Error loading conversations',
    'errors.loadingConversationsDetail': 'An error occurred while loading conversations:',
    'errors.fetchingUserDetails': 'Error fetching user details',
    'errors.titleRequired': 'Please enter a title',
    'errors.descriptionRequired': 'Please enter a description',
    'errors.durationRequired': 'Please enter duration information',
    'errors.userIdNotFound': 'User ID not found. Please log in again.',
    'errors.sessionNotFound': 'Session information not found. Please log in again.',
    'errors.listingCreationError': 'An error occurred while creating the listing',
    'errors.listingCreationErrorTryAgain': 'An error occurred while creating the listing. Please try again later.',
    'errors.loginRequired': 'You need to log in to download this resource.',
    'errors.noDownloadPermission': 'You do not have permission to download this resource.',
    'errors.invalidUniversity': 'Please select a valid university',
    'errors.invalidDepartment': 'Please select a valid department',
    'errors.invalidLinkedInUrl': 'Invalid LinkedIn URL',
    'errors.prohibitedContentDetected': 'Inappropriate content detected. Please edit the text.',
    'errors.projectCreationFailed': 'Failed to create project',
    'errors.courseRequired': 'Please enter the course name',
    
    // Footer
    'footer.platformDescription': 'Kavunla is a platform that brings students together with instructors and shapes the future of education.',
    'footer.quickLinks': 'Quick Links',
    'footer.legal': 'Legal',
    'footer.termsOfUse': 'Terms of Use',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.pdpl': 'PDPL',
    'footer.contact': 'Contact',
    'footer.allRightsReserved': 'All rights reserved.',
    'footer.support': 'Support',
    'footer.security': 'Security',
    'footer.notification': 'Notification',
  },
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('tr');
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      const savedLanguage = localStorage.getItem('language') as Language;
      if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
        setLanguage(savedLanguage);
      }
      setMounted(true);
    }
  }, []);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem('language', language);
    }
  }, [language]);

  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language][key] || key;
    if (params) {
      Object.keys(params).forEach(param => {
        translation = translation.replace(`{${param}}`, params[param]);
      });
    }
    return translation;
  };

  if (!mounted) {
    return <div />;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Custom hook
export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
